CREATE TABLE AULA_REFERENCE (
    ID  NUMBER,
    DESCRICAO VARCHAR2(30)
);


CREATE SEQUENCE MINHA_SEQUENCIA;

SELECT MINHA_SEQUENCIA.NEXTVAL FROM DUAL;

INSERT INTO AULA_REFERENCE VALUES(MINHA_SEQUENCIA.NEXTVAL, 'TESTE VERGS');

SELECT * FROM AULA_REFERENCE ORDER BY 1;

CREATE SEQUENCE SQ_2 START WITH 10 INCREMENT BY 5;

CREATE SEQUENCE SQ_3 START WITH 10 INCREMENT BY 5 MAXVALUE 200;